apps/mailing/urls.py
from django.urls import path
from apps.mailing.apps import MailingConfig
from apps.mailing.views import (
    MailingListView,
    MailingDetailView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
    LogListView,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", MailingListView.as_view(), name="mailing_list"),
    path("<int:pk>", MailingDetailView.as_view(), name="mailing_detail"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("update/<int:pk>", MailingUpdateView.as_view(), name="mailing_update"),
    path("delete/<int:pk>", MailingDeleteView.as_view(), name="mailing_delete"),
    path("<int:mailing_pk>/logs/", LogListView.as_view(), name="log_list"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main.urls", namespace="main")),
    path("clients/", include("apps.client.urls", namespace="clients")),
    path("messages/", include("apps.message.urls", namespace="messages")),
    path("mailings/", include("apps.mailing.urls", namespace="mailings")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("blog/", include("apps.blog.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import IndexView
from main.apps import MainConfig

app_name = MainConfig.name
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

apps/mailing/models.py
from datetime import timedelta
from django.conf import settings
from django.db import models
from django.utils import timezone
from apps.client.models import Client
from apps.message.models import Message
from django.utils.translation import gettext as _
from apps.main.utils import NULLABLE


class Mailing(models.Model):
    """Модель рассылки"""

    class PeriodicityOfMailing(models.TextChoices):
        ONCE_TIME = "Один раз", _("Один раз")
        ONCE_DAY = "Ежедневно", _("Ежедневно")
        ONCE_WEEK = "Еженедельно", _("Еженедельно")
        ONCE_MONTH = "Ежемесячно", _("Ежемесячно")

    class StatusOfMailing(models.TextChoices):
        CREATED = "Создана", _("Создана")
        LAUNCHED = "Запущена", _("Запущена")
        FINISHED = "Завершена", _("Завершена")

    name = models.CharField(max_length=50, verbose_name="Название")
    data_mailing = models.DateTimeField(
        default=timezone.now, verbose_name="Дата создания"
    )
    sent_time = models.DateTimeField(default=timezone.now, verbose_name="Дата отправки")
    data_mailing_finish = models.DateTimeField(
        default=timezone.now() + timedelta(days=365), verbose_name="Дата завершения"
    )
    periodicity = models.CharField(
        default=PeriodicityOfMailing.ONCE_TIME,
        choices=PeriodicityOfMailing,
        verbose_name="Периодичность",
    )
    client_mailing = models.ManyToManyField(Client, verbose_name="Получатели")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Создатель",
        **NULLABLE,
    )
    status = models.CharField(
        default=StatusOfMailing.CREATED, choices=StatusOfMailing, verbose_name="Статус"
    )
    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, verbose_name="Сообщение", default=None
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"

    permissions = [
        ("set_deactivate", "Can deactivate mailing"),
        ("view_all_mailing", "Can view all mailing"),
    ]


class Logs(models.Model):
    """Модель логов рассылки"""

    class StatusOfLogs(models.TextChoices):
        SUCCESS = "Успешно", _("Успешно")
        FAILED = "Безуспешно", _("Безуспешно")

    mailing = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name="Рассылка"
    )
    datatime = models.DateTimeField(verbose_name="Дата и время попытки")
    status = models.CharField(choices=StatusOfLogs, verbose_name="Статус")
    answer_mail_server = models.TextField(verbose_name="Ответ почтового сервера")

    def __str__(self):
        return f"{self.datatime} | {self.mailing} | {self.status} | {self.answer_mail_server}"

    class Meta:
        verbose_name = "Попытка"
        verbose_name_plural = "Попытки"

apps/mailing/forms.py
from django import forms

from apps.mailing.models import Mailing
from apps.main.utils import StyleFormMixin


class MailingForm(StyleFormMixin, forms.ModelForm):
    """Форма создания и редактирования рассылки"""

    class Meta:
        model = Mailing
        exclude = (
            "data_mailing",
            "owner",
        )


class ManagerMailingForm(StyleFormMixin, forms.ModelForm):
    """Форма редактирования рассылки для менеджера"""

    class Meta:
        model = Mailing
        fields = ("status",)

apps/mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from apps.client.models import Client
from apps.mailing.forms import MailingForm, ManagerMailingForm
from apps.mailing.models import Mailing, Logs
from apps.main.utils import AccessCheckMixin
from apps.message.models import Message


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер просмотра списка рассылок"""

    model = Mailing
    extra_context = {"title": "Рассылки"}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name="manager").exists():
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingDetailView(LoginRequiredMixin, DetailView):
    """Контроллер просмотра одной рассылки"""

    model = Mailing
    extra_context = {"title": "Информация о рассылке"}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if (
            not user.is_superuser
            and not user.groups.filter(name="manager").exists()
            and user != self.object.owner
        ):
            raise PermissionDenied
        return self.object


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания рассылки"""

    model = Mailing
    form_class = MailingForm
    extra_context = {"title": "Создание рассылки"}
    success_url = reverse_lazy("mailings:mailing_list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        form.fields["client_mailing"].queryset = Client.objects.filter(owner=user)
        form.fields["message"].queryset = Message.objects.filter(owner=user)
        return form

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования рассылки"""

    model = Mailing
    form_class = MailingForm
    extra_context = {"title": "Редактирование рассылки"}

    def get_success_url(self):
        return reverse("mailings:mailing_detail", args=[self.kwargs.get("pk")])

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            form.fields["client_mailing"].queryset = Client.objects.filter(owner=user)
            form.fields["message"].queryset = Message.objects.filter(owner=user)
        return form

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingForm
        elif user.groups.filter(name="manager").exists():
            return ManagerMailingForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if (
            not user.is_superuser
            and user != self.object.owner
            and not user.groups.filter(name="manager").exists()
        ):
            raise PermissionDenied
        return self.object


class MailingDeleteView(LoginRequiredMixin, AccessCheckMixin, DeleteView):
    """Контроллер удаления рассылки"""

    model = Mailing
    extra_context = {"title": "Удаление рассылки"}
    success_url = reverse_lazy("mailings:mailing_list")


class LogListView(LoginRequiredMixin, ListView):
    """Контроллер просмотра логов рассылки"""

    model = Logs
    extra_context = {"title": "Лог рассылок"}

    def get_queryset(self, *args, **kwargs):
        mailing_pk = self.kwargs.get("mailing_pk")
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(mailing__pk=mailing_pk)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["mailing_pk"] = self.kwargs.get("mailing_pk")
        return context

    def dispatch(self, request, *args, **kwargs):
        mailing_pk = self.kwargs.get("mailing_pk")
        user = self.request.user
        if (
            not user.is_superuser
            and not Mailing.objects.filter(pk=mailing_pk, owner=user).exists()
        ):
            raise PermissionDenied
        return super().dispatch(request, args, **kwargs)

apps/mailing/templates/mailing/logs_list.html
{% extends 'main/base.html' %}
{% block content %}
<a href="{% url 'mailings:mailing_detail' mailing_pk %}" class="btn btn-outline-info btn-block mb-3">
    Вернуться к рассылке
</a>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Название рассылки</th>
        <th scope="col">Дата и время отправки</th>
        <th scope="col">Статус</th>
        <th scope="col">Ответ сервера</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ object.mailing }}</td>
        <td>{{ object.datatime}}</td>
        <td>{{ object.status}}</td>
        <td>{{ object.answer_mail_server}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

apps/mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
<div class="row justify-content-center">
    <div class="col-5 card">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <p>Вы действительно хотите удалить рассылку: <i>{{ object.name }}.</i></p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'mailings:mailing_detail' object.pk %}" class="btn btn-warning">Отменить</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

apps/mailing/templates/mailing/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
{% load user_tags %}
<h2 class="text-center mb-3">{{ title }}</h2>
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Название</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td>Создатель</td>
                        <td>{{ object.owner }}</td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td>{{ object.data_mailing }}</td>
                    </tr>
                    <tr>
                        <td>Следующая отправка</td>
                        <td>{{ object.sent_time }}</td>
                    </tr>
                    <tr>
                        <td>Дата завершения</td>
                        <td>{{ object.data_mailing_finish }}</td>
                    </tr>
                    <tr>
                        <td>Периодичность</td>
                        <td>{{ object.periodicity }}</td>
                    </tr>
                    <tr>
                        <td>Получатели</td>
                        <td>
                            {% for client in object.client_mailing.all %}
                            {{ client.firstname }} {{ client.lastname|slice:1 }}. {{ client.surname|slice:1 }}.
                            {% if not forloop.last %}|{% endif%}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>Статус</td>
                        <td>{{ object.status }}</td>
                    </tr>
                    <tr>
                        <td>Сообщение</td>
                        <td>{{ object.message }}</td>
                    </tr>
                </table>
            </div>
            <div class="card-footer">
                {% if user == object.owner or user.is_superuser or user|is_manager %}
                <a href="{% url 'mailings:mailing_update' object.pk %}" class="btn btn-outline-info btn-block">
                    Редактировать
                </a>
                {% endif %}
                {% if user == object.owner or user.is_superuser %}
                <a href="{% url 'mailings:mailing_delete' object.pk %}"
                   class="btn btn-outline-danger btn-block">Удалить</a>
                <a href="{% url 'mailings:log_list' object.pk %}"
                   class="btn btn-outline-warning btn-block">Посмотреть логи</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/mailing/templates/mailing/mailing_form.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
<div class="row justify-content-center">
    <section class="col-6 card ">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-outline-info form-control">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

apps/mailing/templates/mailing/mailing_list.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
{% if user.is_authenticated %}
<a href="{% url 'mailings:mailing_create' %}" class="btn btn-outline-info btn-block mb-3">
    Добавить рассылку
</a>
{% endif %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Название</th>
        <th scope="col">Дата начала</th>
        <th scope="col">Дата завершения</th>
        <th scope="col">Периодичность</th>
        <th scope="col">Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row">
            <a href="{% url 'mailings:mailing_detail' object.pk %}" class="btn btn-sm btn-outline-info">
                {{ forloop.counter }}
            </a>
        </th>
        <td>{{ object.name }}</td>
        <td>{{ object.data_mailing}}</td>
        <td>{{ object.data_mailing_finish}}</td>
        <td>{{ object.periodicity}}</td>
        <td>{{ object.status}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}