apps/users/urls.py
from django.urls import path

from apps.users.apps import UsersConfig
from apps.users.views import (
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
    email_verification,
    UserUpdateView,
    UserPasswordResetView,
    UserListView,
    toggle_activiti,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("confirm-email/<str:token>/", email_verification, name="confirm-email"),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("recovery/", UserPasswordResetView.as_view(), name="recovery"),
    path("", UserListView.as_view(), name="user_list"),
    path("toggle_activiti/<int:pk>", toggle_activiti, name="toggle_activiti"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main.urls", namespace="main")),
    path("clients/", include("apps.client.urls", namespace="clients")),
    path("messages/", include("apps.message.urls", namespace="messages")),
    path("mailings/", include("apps.mailing.urls", namespace="mailings")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("blog/", include("apps.blog.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import IndexView
from main.apps import MainConfig

app_name = MainConfig.name
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    """Модель пользователя"""

    username = None

    email = models.EmailField(unique=True, verbose_name="Email")
    first_name = models.CharField(max_length=50, verbose_name="Имя", **NULLABLE)
    last_name = models.CharField(max_length=50, verbose_name="Фамилия", **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name="Телефон", **NULLABLE)
    country = models.CharField(max_length=100, verbose_name="Страна", **NULLABLE)
    avatar = models.ImageField(
        upload_to="users/avatars/", verbose_name="Аватар", **NULLABLE
    )
    token = models.CharField(max_length=120, verbose_name="Токен", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("set_user_deactivate", "Can user deactivate"),
            ("view_all_users", "Can view all users"),
        ]

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
    PasswordResetForm,
)
from apps.main.utils import StyleFormMixin
from django.forms import BooleanField

from apps.users.models import User


class LoginForm(StyleFormMixin, AuthenticationForm):
    """Форма входа пользователя"""

    pass


class RegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации пользователя"""

    class Meta:
        model = User
        fields = (
            "email",
            "password1",
            "password2",
        )


class UserForm(StyleFormMixin, UserChangeForm):
    """Форма редактирования пользователя"""

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone",
            "country",
            "avatar",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()


class RecoveryForm(StyleFormMixin, PasswordResetForm):
    """Форма восстановления пользователя"""

    pass

apps/users/views.py
import secrets
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView
from apps.users.forms import LoginForm, RegisterForm, UserForm, RecoveryForm
from apps.users.models import User
from apps.users.services import make_random_password
from config.settings import EMAIL_HOST_USER


class UserLoginView(LoginView):
    """Контроллер авторизации пользователя"""

    form_class = LoginForm
    template_name = "users/login.html"


class UserLogoutView(LogoutView):
    """Контроллер выхода пользователя"""

    pass


class UserRegisterView(CreateView):
    """Контроллер регистрации пользователя"""

    model = User
    form_class = RegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(15)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/confirm-email/{token}/"
        try:
            send_mail(
                subject="Верификация почты на сайте MailingService",
                message=f"Доброго времени суток! "
                f"Для подтверждения регистрации на сайте MailingService перейдите по ссылки {url}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
        except Exception:
            print(f"Ошибка при отправке письма верификации")
        return super().form_valid(form)


def email_verification(request, token):
    """Контроллер подтверждения регистрации пользователя"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserUpdateView(UpdateView):
    """Контроллер редактирования пользователя"""

    model = User
    form_class = UserForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordResetView(PasswordResetView):
    """Контроллер смены пароля пользователя"""

    form_class = RecoveryForm
    template_name = "users/recovery_form.html"

    def form_valid(self, form):
        if self.request.method == "POST":
            user_email = self.request.POST["email"]
            user = User.objects.filter(email=user_email).first()
            if user:
                password = make_random_password()
                user.set_password(password)
                user.save()
                try:
                    send_mail(
                        subject="Восстановление пароля на сайте MailingService",
                        message=f"Доброго времени суток! "
                        f"Ваш пароль для доступа на сайт MailingService изменен:\n"
                        f"Данные для входа:\n"
                        f"Email: {user_email}\n"
                        f"Пароль: {password}",
                        from_email=EMAIL_HOST_USER,
                        recipient_list=[user.email],
                    )
                except Exception:
                    print(
                        f"Ошибка при отправке пароля юзеру: ({user=}), на email: {user_email}"
                    )
            return HttpResponseRedirect(reverse("users:login"))
        return super().form_valid(form)


class UserListView(PermissionRequiredMixin, ListView):
    """Контроллер просмотра списка пользователей"""

    permission_required = "users.view_all_users"
    model = User
    extra_context = {"title": "Список пользователей"}

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if user.is_superuser:
            return (
                super()
                .get_queryset(*args, **kwargs)
                .exclude(pk=self.request.user.pk)
                .exclude(is_superuser=True)
            )
        return (
            super()
            .get_queryset(*args, **kwargs)
            .exclude(pk=self.request.user.pk)
            .exclude(is_superuser=True)
            .exclude(is_staff=True)
        )


@permission_required("users.set_user_deactivate")
def toggle_activiti(request, pk):
    """Контроллер изменения статуса пользователя"""
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse("users:user_list"))

apps/users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">Авторизация</h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-info form-control">
                        Войти
                    </button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:recovery' %}" class="btn btn-outline-danger">Восстановление пароля</a>
                <a href="{% url 'users:register' %}" class="btn btn-outline-success">Регистрация</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/users/templates/users/recovery_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">
                    Форма восстановления
                </h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="w-100 btn btn-block btn-outline-success">
                        Восстановить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">
                    {% if user.is_authenticated %}
                    Профиль
                    {% else %}
                    Регистрация
                    {% endif %}
                </h4>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="w-100 btn btn-block btn-outline-success">
                        {% if user.is_authenticated %}
                        Сохранить
                        {% else %}
                        Зарегистрироваться
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Email</th>
        <th scope="col">Страна</th>
        <th scope="col">Телефон</th>
        <th scope="col">Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ object.first_name|default:'-' }}</td>
        <td>{{ object.last_name|default:'-' }}</td>
        <td>{{ object.email }}</td>
        <td>{{ object.country|default:'-' }}</td>
        <td>{{ object.phone|default:'-' }}</td>
        <td>
            {% if perms.users.set_user_deactivate or user.is_superuser %}
            {% if object.is_active %}
            <a href="{% url 'users:toggle_activiti' object.pk %}"
               class="btn btn-sm btn-outline-danger">Деактивировать</a>
            {% else %}
            <a href="{% url 'users:toggle_activiti' object.pk %}"
               class="btn btn-sm btn-outline-success">Активировать</a>
            {% endif %}
            {% endif %}
        </td>
        <td></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}