apps/message/urls.py
from django.urls import path
from apps.message.apps import MessageConfig
from apps.message.views import (
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
)

app_name = MessageConfig.name

urlpatterns = [
    path("", MessageListView.as_view(), name="message_list"),
    path("<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path("create/", MessageCreateView.as_view(), name="message_create"),
    path("update/<int:pk>", MessageUpdateView.as_view(), name="message_update"),
    path("delete/<int:pk>", MessageDeleteView.as_view(), name="message_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main.urls", namespace="main")),
    path("clients/", include("apps.client.urls", namespace="clients")),
    path("messages/", include("apps.message.urls", namespace="messages")),
    path("mailings/", include("apps.mailing.urls", namespace="mailings")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("blog/", include("apps.blog.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import IndexView
from main.apps import MainConfig

app_name = MainConfig.name
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

apps/message/models.py
from django.conf import settings
from django.db import models

from apps.main.utils import NULLABLE


class Message(models.Model):
    """Модель сообщение в рассылке"""

    letter_subject = models.CharField(max_length=150, verbose_name="Тема письма")
    letter_body = models.TextField(verbose_name="Тело письма")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Создатель",
        **NULLABLE,
    )

    def __str__(self):
        return f"{self.letter_subject}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

apps/message/forms.py
from django import forms
from apps.main.utils import StyleFormMixin
from apps.message.models import Message


class MessageForm(StyleFormMixin, forms.ModelForm):
    """Форма создания и редактирования сообщения"""

    class Meta:
        model = Message
        exclude = ("owner",)

apps/message/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from apps.main.utils import AccessCheckMixin
from apps.message.forms import MessageForm
from apps.message.models import Message


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер просмотра списка сообщений"""

    model = Message
    extra_context = {"title": "Сообщения"}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if not user.is_superuser:
            queryset = queryset.filter(owner=user)
        return queryset


class MessageDetailView(LoginRequiredMixin, AccessCheckMixin, DetailView):
    """Контроллер просмотра одного сообщения"""

    model = Message
    extra_context = {"title": "Информация о сообщении"}


class MessageCreateView(CreateView):
    """Контроллер создания сообщения"""

    model = Message
    form_class = MessageForm
    extra_context = {"title": "Создание сообщения"}
    success_url = reverse_lazy("messages:message_list")

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, AccessCheckMixin, UpdateView):
    """Контроллер редактирования сообщения"""

    model = Message
    form_class = MessageForm
    extra_context = {"title": "Редактирование сообщения"}

    def get_success_url(self):
        return reverse("messages:message_detail", args=[self.kwargs.get("pk")])


class MessageDeleteView(LoginRequiredMixin, AccessCheckMixin, DeleteView):
    """Контроллер удаления сообщения"""

    model = Message
    extra_context = {"title": "Удаление сообщения"}
    success_url = reverse_lazy("messages:message_list")

apps/message/templates/message/message_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
<div class="row justify-content-center">
    <div class="col-5 card">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <p>Вы действительно хотите удалить сообщение: <i>{{ object.letter_subject }}.</i></p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'messages:message_detail' object.pk %}" class="btn btn-warning">Отменить</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/message/templates/message/message_detail.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Тема</td>
                        <td>{{ object.letter_subject }}</td>
                    </tr>
                    <tr>
                        <td>Текст</td>
                        <td>{{ object.letter_body }}</td>
                    </tr>
                </table>
            </div>
            {% if user == object.owner or user.is_superuser %}
            <div class="card-footer">
                <a href="{% url 'messages:message_update' object.pk %}" class="btn btn-outline-info btn-block">Редактировать</a>
                <a href="{% url 'messages:message_delete' object.pk %}"
                   class="btn btn-outline-danger btn-block">Удалить</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

apps/message/templates/message/message_form.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
<div class="row justify-content-center">
    <section class="col-12 card ">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-outline-info form-control">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

apps/message/templates/message/message_list.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="text-center mb-3">{{ title }}</h2>
{% if user.is_authenticated %}
<a href="{% url 'messages:message_create' %}" class="btn btn-outline-info btn-block mb-3">
    Добавить сообщение
</a>
{% endif %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Тема письма</th>
        <th scope="col">Тело письма</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row"><a href="{% url 'messages:message_detail' object.pk %}" class="btn btn-sm btn-outline-info">
            {{ forloop.counter }}
        </a>
        </th>
        <td>{{ object.letter_subject }}</td>
        <td>{{ object.letter_body | slice:100 }}...</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}