apps/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from apps.blog.apps import BlogConfig
from apps.blog.views import (
    ArticleListView,
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", ArticleListView.as_view(), name="article_list"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
    path(
        "view/<slug:slug>",
        cache_page(60)(ArticleDetailView.as_view()),
        name="article_view",
    ),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="article_update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="article_delete"),
]

apps/client/urls.py
from django.urls import path
from apps.client.apps import ClientConfig

from apps.client.views import (
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
)

app_name = ClientConfig.name
urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("<int:pk>", ClientDetailView.as_view(), name="client_detail"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("update/<int:pk>", ClientUpdateView.as_view(), name="client_update"),
    path("delete/<int:pk>", ClientDeleteView.as_view(), name="client_delete"),
]

apps/mailing/urls.py
from django.urls import path
from apps.mailing.apps import MailingConfig
from apps.mailing.views import (
    MailingListView,
    MailingDetailView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
    LogListView,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", MailingListView.as_view(), name="mailing_list"),
    path("<int:pk>", MailingDetailView.as_view(), name="mailing_detail"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("update/<int:pk>", MailingUpdateView.as_view(), name="mailing_update"),
    path("delete/<int:pk>", MailingDeleteView.as_view(), name="mailing_delete"),
    path("<int:mailing_pk>/logs/", LogListView.as_view(), name="log_list"),
]

apps/main/urls.py
from django.urls import path

from apps.main.apps import MainConfig
from apps.main.views import IndexView

app_name = MainConfig.name

urlpatterns = [path("", IndexView.as_view(), name="home")]

apps/users/urls.py
from django.urls import path

from apps.users.apps import UsersConfig
from apps.users.views import (
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
    email_verification,
    UserUpdateView,
    UserPasswordResetView,
    UserListView,
    toggle_activiti,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("confirm-email/<str:token>/", email_verification, name="confirm-email"),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("recovery/", UserPasswordResetView.as_view(), name="recovery"),
    path("", UserListView.as_view(), name="user_list"),
    path("toggle_activiti/<int:pk>", toggle_activiti, name="toggle_activiti"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main.urls", namespace="main")),
    path("clients/", include("apps.client.urls", namespace="clients")),
    path("messages/", include("apps.message.urls", namespace="messages")),
    path("mailings/", include("apps.mailing.urls", namespace="mailings")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("blog/", include("apps.blog.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import IndexView
from main.apps import MainConfig

app_name = MainConfig.name
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

apps/main/views.py
from django.views.generic import TemplateView

from apps.blog.models import Article
from apps.client.models import Client
from apps.mailing.models import Mailing
from apps.main.utils import get_random_articles_from_cache


class IndexView(TemplateView):
    extra_context = {"title": "Главная"}
    template_name = "main/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        mailing = Mailing.objects.all()
        clients = Client.objects.all()
        context["count_mailing"] = mailing.count()
        context["count_mailing_active"] = mailing.filter(
            status=Mailing.StatusOfMailing.LAUNCHED
        ).count()
        context["articles_random"] = Article.objects.all()
        context["count_client"] = clients.count()
        context["count_client_unique"] = clients.values("email").distinct().count()
        context["object_list"] = get_random_articles_from_cache(3)
        return context

apps/main/templates/main/includes/inc_menu.html
<nav class="navbar navbar-expand-xl navbar-custom">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:home' %}">
            Mailing<span>service</span>
        </a>
        <div class="collapse navbar-collapse show" id="navbarBasic">
            <ul class="navbar-nav ms-auto gap-3">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:home' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:article_list' %}">Блог</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clients:client_list' %}">Клиенты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'messages:message_list' %}">Сообщения</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mailings:mailing_list' %}">Рассылки</a>
                </li>
                {% if perms.users.view_all_users %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:user_list' %}">Пользователи</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                </li>
                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="mt-2 btn btn-danger">Выйти</button>
                </form>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link btn-default" href="{% url 'users:login' %}">Войти | Регистрация</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>